export const textNodeConfig = {
  title: "Text",
  type: "text",
  width: 230,
  bgColor: "#f0fdf4",
  borderColor: "#22c55e",
  titleColor: "#15803d",

  fields: [
    {
      name: "text",
      label: "Content",
      type: "textarea",
      defaultValue: "{{input}}",
      placeholder: "Use {{variable}} for dynamic handles",
    },
  ],

  // Dynamic input handles are generated by Part 3 TextNode logic
  // TODO PART  - 3: Implement dynamic input handles based on the text content and variable placeholders
  inputHandles: [{ id: "value", label: "Value", color: "#9333ea" }],
  outputHandles: [{ id: "output", label: "Output", color: "#22c55e" }],
};
